// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7d3gRu3nP7k3k2iSqbT7fy9ZHBkpkRN8',
    appId: '1:298580599577:web:fc315e25ac7124fc1d1b88',
    messagingSenderId: '298580599577',
    projectId: 'godoc-4d7a8',
    authDomain: 'godoc-4d7a8.firebaseapp.com',
    storageBucket: 'godoc-4d7a8.firebasestorage.app',
    measurementId: 'G-KWX327CLDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2AojDKizh7-E3uEddLntC5U8_CZODy8w',
    appId: '1:298580599577:android:6f494fc6774de2e21d1b88',
    messagingSenderId: '298580599577',
    projectId: 'godoc-4d7a8',
    storageBucket: 'godoc-4d7a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI7eL6Cx69UerTrt_EyFqxTpL5sMe1PFY',
    appId: '1:298580599577:ios:adb5eeae40da36a41d1b88',
    messagingSenderId: '298580599577',
    projectId: 'godoc-4d7a8',
    storageBucket: 'godoc-4d7a8.firebasestorage.app',
    iosBundleId: 'com.example.godoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI7eL6Cx69UerTrt_EyFqxTpL5sMe1PFY',
    appId: '1:298580599577:ios:adb5eeae40da36a41d1b88',
    messagingSenderId: '298580599577',
    projectId: 'godoc-4d7a8',
    storageBucket: 'godoc-4d7a8.firebasestorage.app',
    iosBundleId: 'com.example.godoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7d3gRu3nP7k3k2iSqbT7fy9ZHBkpkRN8',
    appId: '1:298580599577:web:8d6c6f6db0210c1e1d1b88',
    messagingSenderId: '298580599577',
    projectId: 'godoc-4d7a8',
    authDomain: 'godoc-4d7a8.firebaseapp.com',
    storageBucket: 'godoc-4d7a8.firebasestorage.app',
    measurementId: 'G-CPRDYHSE89',
  );

}