import 'package:firebase_core/firebase_core.dart';

import 'firestore_data_service.dart';
import '../../firebase_options.dart';

Future<void> bootstrapFirebase() async {
  // This app supports web + mobile. Web requires explicit Firebase options.
  // See `lib/firebase_options.dart` (generated by `flutterfire configure`).
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Seed local app state into Firestore (if empty) and keep app state in sync.
  await FirestoreDataService.instance.seedAndSync();
}
